### ISSUE TITLE
`stub_request` param `uri_regex` doesn't allow for regex in the uri path

### ISSUE THREAD

**Issue by dgkf** [ropensci/webmockr#106]
<details> <summary><strong>Session Info</strong></summary>

```r
# starting a new R session
> sessionInfo()
#> R version 4.0.2 (2020-06-22)
#> Platform: x86_64-conda_cos6-linux-gnu (64-bit)
#> Running under: Ubuntu 20.04.1 LTS
#> 
#> Matrix products: default
#> BLAS/LAPACK: /home/name/.miniconda3/envs/R/lib/libopenblasp-r0.3.7.so
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
#>  [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] httr_1.4.2     webmockr_0.6.2
#> 
#> loaded via a namespace (and not attached):
#> [1] compiler_4.0.2 magrittr_1.5   R6_2.4.1       whisker_0.4    httpcode_0.3.0 curl_4.3       fauxpas_0.5.0  crul_1.0.0    

```
</details>

I'm trying to figure out how to use `stub_request("any", uri_regex = <regex>)`, but running into a bunch of problems trying to interpret the correct behavior. From what I can tell, regular expressions in the uri path aren't respected. The documentation for the `uri_regex` parameter doesn't state which parts can be used as a regular expression. If this is intended behavior, perhaps it is worth clarifying which parts of the uri are interpreted as regex.

From what I can tell, this all boils down to how regular expressions are handled in `normalize_uri`, escaping the path portion of the uri regardless of whether regular expressions are allowed. 

https://github.com/ropensci/webmockr/blob/7b9508d448edb2ed501f4a7b6950f67de18815ca/R/RequestPattern.R#L610

# Example

This is the use case that I'm trying to use this for, querying the github.com "repos" api

```r
webmockr::enable()
httr_mock()

stub_request("get", uri_regex = "api.github.com/repos/.+/.+/") %>%
  to_return(body = "test body")

GET("https://api.github.com/repos/ropensci/webmockr")
#> Error: Real HTTP connections are disabled.
#> Unregistered request:
#>   GET:  https://api.github.com/repos/ropensci/webmockr   with headers {Accept: application/json, text/xml, application/xml, */*}
#> 
#> You can stub this request with the following snippet:
#> 
#>    stub_request('get', uri = 'https://api.github.com/repos/ropensci/webmockr') %>%
#>      wi_th(
#>        headers = list('Accept' = 'application/json, text/xml, application/xml, */*')
#>      )
#> 
#> registered request stubs:
#> 
#>  GET: api.github.com/repos/.+/.+/   | to_return:  with body "./test_webmocks/github_repo_api_response.json"   with headers {"Content-Type":"ap
#> plication/json"}
```

Trying to narrow down the scope of the error a bit:

```r
x <- UriPattern$new(regex_pattern = "api\\.github\\.com/repos/.+/.+/")
x$pattern
#> [1] "https?://api\\.github\\.com/repos%2F.%2B%2F.%2B"
```

**Comment by sckott** [comment]
thanks @dgkf for the issue  - having a look

**Comment by sckott** [comment]
> The documentation for the uri_regex parameter doesn't state which parts can be used as a regular expression. 

what do you mean by which parts? the whole string given to `uri_regex` is a regex string, so any parts of it. e.g., you can just give `.+`

**Comment by dgkf** [comment]
Thanks for the update @sckott,

> > The documentation for the uri_regex parameter doesn't state which parts can be used as a regular expression.
> 
> what do you mean by which parts? the whole string given to `uri_regex` is a regex string, so any parts of it. e.g., you can just give `.+`

I wasn't sure if it was intended behavior to escape the uri path components. My interpretation based on the documentation was that the whole uri should be treated as regex, but I wasn't sure.

---

This looks like it solved this issue with the regular expressions in the uri host and paths, but I think in the process of testing it I've dug up another bug or two related path matching and query parameters. I'll file a separate issue once I've done my due diligence to try to narrow it down a bit.

**Comment by sckott** [comment]
thanks
