### ISSUE TITLE
bug, possibly related to simple auth

### ISSUE THREAD

**Issue by sckott** [ropensci/webmockr#108]
via @mpadge in slack

mark, what repo is this? what test is throwing the error

**Comment by mpadge** [comment]
The test which triggers it is in [`mpadge/allcontributor`](https://github.com/mpadge/allcontributor/blob/master/tests/testthat/test-get-contribs.R), with the failing workflow [here](https://github.com/mpadge/allcontributor/runs/1247105338?check_suite_focus=true). Note that I'm mocking `httr` body and headers elements, but not options. Maybe [this line in `adapter_httr`](https://github.com/ropensci/webmockr/blob/master/R/adapter-httr.R#L69) is not returning `NULL`, leading to construction of a garbage `auth_header`? The github repo has a bunch of secrets, including `GH_TOKEN`.

**Comment by sckott** [comment]
thanks @mpadge will be hard to address this if I can't replicate it. Can you replicate the problem locally or only on CI?  I asked in slack if you can share what secrets are in the repo, may help diagnosing. 

>  Maybe this line in adapter_httr is not returning NUL

I don't think that's the issue. The function under test `get_contributors` appears to set simple auth if a token is found, so i'm guessing this line https://github.com/mpadge/allcontributor/blob/master/R/github.R#L14 does return a token, so that this route in the if/else is taken https://github.com/mpadge/allcontributor/blob/master/R/github.R#L25-L26 - If so, I need to know what `userpwd` field in the httr request is on your CI build. Seems maybe it's not as I expect a string like `foo:bar` which would fail here https://github.com/ropensci/webmockr/blob/master/R/adapter-httr.R#L71

**Comment by mpadge** [comment]
This is going to frustrate you as much as me here, but ... I can't reproduce it. I've tried every conceivable option of explicitly malforming all relevant variables, but the errors all get caught before triggering the one on the github actions build. I've got a new [test file](https://github.com/mpadge/allcontributor/blob/master/tests/testthat/test-aa.R) which confirms that all expected envvars are present, and that `httr::authenticate()` parses as expected. I'll reduce to a minimal test repo to try to isolate the cause more precisely ...

**Comment by mpadge** [comment]
okay, i got to the bottom of it, and it's all kinda my fault. My attempts at grabbing tokens were getting mucked up by github's own [default envvars](https://docs.github.com/en/free-pro-team@latest/actions/reference/environment-variables#default-environment-variables), so that a URL was returned instead of a token. This issue can either just be closed, or maybe if you want to provide a little more helpful info to others in the future, check to ensure that the `auth` variable in your adapters is a "genuine" hash. That is, of course, a bag o'worms, as you can't know how any website has implemented authentication, let alone what kind of hash they are generating. But maybe you could throw out a couple of obvious non-hash-like candidates such as `^http(s?)//`, which would have caught my case?

**Comment by sckott** [comment]
Ugh, sorry for delay on this Mark. vacation and then fell to bottom of emails. thanks for persisting. 

I do want to help others avoid this issue in the future for sure. I'll look into that

**Comment by sckott** [comment]
Hmm, was going to add some other logic besides detecting URLs in the userpwd, but it appears the RFC only states that user names can't contain colons, but there's no way to know that on the webmockr side because webmockr recieves the userpwd already concatenated into a single colon sep string - so there's no way to know in the case of multiple colons if the 1st colon is the separator (in which case, all is good) or the 2nd one is (in which case the user name is invalid) - seems that stuff needs to be done within each http client

**Comment by sckott** [comment]
@mpadge made a fix, if you could test that'd be great, but if you already have a different fix you're happy with no worries

**Comment by mpadge** [comment]
Thanks @sckott, i already implemented a fix myself, but it's very similar to your new [`check_user_pwd() function](https://github.com/ropensci/webmockr/commit/03ce53f0302390e971f11cccbf878d51d14f042f#diff-1aff2e93c261377578034e1bf31ae447b751883b68538ee82f01a3cf39ae308bR65-R71), so I'm sure everything will be fine now. Pretty sure you can close this now.

**Comment by sckott** [comment]
thanks mark
