### ISSUE TITLE
to_return() doesn't accept integer for status

### ISSUE THREAD

**Issue by maelle** [ropensci/webmockr#117]
the docs say it could be an integer, but the assertion is that it is a numeric.

``` r
library("webmockr")
foo <- function() {
  stub_request("post", "https://httpbin.org/post")
}

foo() %>% to_return(status = 200L)
#> Error: z$status must be of class numeric
```

<sup>Created on 2022-08-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by sckott** [comment]
oopsy. will fix that
