### ISSUE TITLE
Remove any pipe usage in the package

### ISSUE THREAD

**Issue by sckott** [ropensci/webmockr#30]
exporting pipe is still good idea for users, but remove from within pkg

**Comment by maelle** [comment]
oh should it be a general rule/recommendation over all packages and if so why? Would you want to write a blurb about this 🔥 controversial topic 🔥 for the ropenscilabs/dev_guide?

**Comment by sckott** [comment]
ha, no, i do not want to publicly take a stand on this. I just personally want to avoid them
