### ISSUE TITLE
Retries

### ISSUE THREAD

**Issue by maelle** [ropensci/webmockr#31]
Related to https://github.com/ropensci/webmockr/issues/4#issuecomment-380758836

How would one test for the case when the API returns 429 say 3 times and then 200? How could I stub that in a test?

**Comment by sckott** [comment]
Thanks for raising the issue! 

We don't support it yet. There's two things we need i think. 

- support for `times` see #10 - so ones can say how many times they want a given response given back
- support for `then`, to support see #32

**Comment by maelle** [comment]
cool, am excited for it to be supported in the future! should I close this issue or let it open to remember to write an example or something?

**Comment by sckott** [comment]
can leave it open i think for now, will label it a use case, then we can include as an example

**Comment by maelle** [comment]
Re-visiting ropenaq tests, I'm very interested in this.

**Comment by sckott** [comment]
okay, will bump this up in the priority list

**Comment by maelle** [comment]
When this works won't it be easier to test the "retry" method in crul? :slightly_smiling_face:

**Comment by sckott** [comment]
yes, good point

**Comment by sckott** [comment]
@maelle okay, we have support for multiple responses now - the `then` branch is now merged to master. something like:

```r
library(webmockr)
enable()

stub_request("get", "https://httpbin.org/get") %>% 
  to_return(status = 429, body = "retry!", times = 3) %>% 
  to_return(status = 200, body = "yay, success!")

res <- crul::HttpClient$new("https://httpbin.org/get")$retry("get", verbose = TRUE)
res$parse("UTF-8")
```

**Comment by maelle** [comment]
That's really nice. I was thinking about using this for ropenaq tests but in ropenaq I use the crul retry method for non async and hope that there will be a crul retry method for async. This way no need for me to test for that in ropenaq... I'll try to make a PR to add a test to crul.

**Comment by maelle** [comment]
mmmh actually I also add a test to ropenaq.
