### ISSUE TITLE
Support partial matching ?

### ISSUE THREAD

**Issue by sckott** [ropensci/webmockr#38]
partially including a hash

- body https://github.com/bblimke/webmock#matching-request-body-against-partial-hash
- query params https://github.com/bblimke/webmock#matching-partial-query-params-using-hash

partially excluding a hash

- query eg. https://github.com/bblimke/webmock#matching-partial-query-params-using-hash_excluding but should work on both

some links on partial matching so I don't lose them
- https://stackoverflow.com/questions/59186442/how-can-i-get-webmock-to-match-a-body-containing-specific-xml-data-using-hash-in/70762720#70762720
- https://stackoverflow.com/questions/16512140/using-webmock-to-stub-partial-headers/16518268#16518268

**Comment by sckott** [comment]
- [x] query params: include
- [x] query params: exclude
- [ ] request body: include
- [ ] request body: exclude

**Comment by sckott** [comment]
@maelle @aaronwolen if either of you have time - i'd be interested to see what you think of this partial matching stuff. Only query matching is done so far; hope to get request body matching done soon

```r
remotes::install_github("ropensci/webmockr@including")
library(webmockr)
library(crul)
enable()
stub_request("get", "https://httpbin.org/get") %>% 
  wi_th(query = including(list(foo = "bar")))
HttpClient$new("https://httpbin.org")$get("get", query = list(foo = "bar"))
```

**Comment by aaronwolen** [comment]
Sure, I'll test it out. I might actually have a use case for it too!

**Comment by sckott** [comment]
thanks!

**Comment by sckott** [comment]
@aaronwolen did you have a chance to test this?

**Comment by sckott** [comment]
`including` branch https://github.com/ropensci/webmockr/tree/including now up to date with master

**Comment by sckott** [comment]
@maelle any time to test this? no worries if not

**Comment by maelle** [comment]
Not before next week, sorry!

**Comment by sckott** [comment]
Okay, thanks

**Comment by aaronwolen** [comment]
Hey @sckott, I did check it out but failed to report back. Apologies! It's definitely a nice feature and everything appeared to work as advertised. 

I also really like the implementation of the `including()`/`excluding()` wrappers. 

One minor usability suggestion: what do you think about giving them a list-like interface so users aren't required to wrap multiple key/vals in `list()`. 

Something like

```r
including <- function(...) {
  structure(check_params(...), partial_match = TRUE, partial_type = "include")
}

excluding <- function(...) {
  structure(check_params(...), partial_match = TRUE, partial_type = "exclude")
}

# verify all args are named
check_params <- function(...) {
  params <- list(...)
  named <- nzchar(names(params) %||% "")
  if (length(params) != sum(named)) {
    stop("All query parameters must be named", call. = FALSE)
  }
  params
}
```

**Comment by sckott** [comment]
Thanks @aaronwolen !

Good idea. Right now `query` is expected to be a named list https://docs.ropensci.org/webmockr/reference/wi_th.html#details  

So if we allowed e.g., `wi_th(req, query = including(foo = "bar"))` would that confuse people if the standard use is `wi_th(req, query = list(foo = "bar"))` ? That is if you normally use `list()`, then with including/excluding they might try `wi_th(req, query = including(list(foo = "bar")))`, which wouldn't work. 

I do like your suggestion as that makes for less code

**Comment by aaronwolen** [comment]
Oh that's a  fair point. I suppose you could add an additional assertion to `check_params()` like

```r
any(vapply(params, is.list, FUN.VALUE = logical(1)))
```

to look for nested lists. Either way, it was just a minor thing, feel free to ignore!

**Comment by sckott** [comment]
The other thing about this is what if a user needs to pass an already created list. e.g., 

```r
x = list(a = 5, b = 6)
including(x) # as is now

# if we changed to function(...) from function(x) we'd need another parameter
including <- function(..., .list = list()) { ... }
including(.list = x)
```

**Comment by sckott** [comment]
Pushing this off until the next milestone. Will give us more time to make sure this is thought through well; supporting partial matching on bodies is going to be complicated, so will be good to have more time

**Comment by maelle** [comment]
Would you use partial matching in tests and if so for what use case?

**Comment by sckott** [comment]
well partial would only work directly with webmockr, not via vcr - an example would be: if you think you may change some aspect of the request in the test and don't want to re-write the stub

**Comment by sckott** [comment]
done 🎉
