### ISSUE TITLE
vignettes

### ISSUE THREAD

**Issue by sckott** [ropensci/webmockr#4]
- [ ] outside of test framework
- [ ] inside of test framework

**Comment by maelle** [comment]
If you validate [these tests](https://github.com/lockedata/HIBPwned/blob/dev/tests/testthat/test-http-errors-handling.R) (or tell me what's wrong 🙏 ) I can volunteer for the "inside of test framework" vignette. 👼

**Comment by sckott** [comment]
thanks for offering!  I guess we need to sort out #31 first though?

**Comment by maelle** [comment]
yes it'd be better

**Comment by maelle** [comment]
In the README and/or a vignette it'd be nice to write, reg tests, _when_ you need to use webmockr. Often you can just use vcr, if needed edit cassettes?
