### ISSUE TITLE
Type of response header value depends on how stub was constructed 

### ISSUE THREAD

**Issue by hlapp** [ropensci/webmockr#48]
For example, if a request stub is constructed with a decimal value for a response header, then the response header obtained from a request has a decimal as the value for the respective header. This may seem natural at first, however for real web requests all values are character vectors, not decimals. Hence, the behavior is inconsistent with real web requests, which kind of defeats the purpose of the package.

Example:
```
library(crul)
library(webmockr)
webmockr::enable()
stub <- webmockr::stub_request(uri = "http://httpbin.org/get") %>%
  webmockr::to_return(headers = list("foo-bar" = 10))
cli <- HttpClient$new(url = "http://httpbin.org/")
resp <- cli$get("get")
resp$response_headers
# $`foo-bar`
# [1] 10

webmockr::stub_registry_clear()
stub <- webmockr::stub_request(uri = "http://httpbin.org/get") %>%
  webmockr::to_return(headers = list("foo-bar" = "10"))
resp <- cli$get("get")
resp$response_headers
# $`foo-bar`
# [1] "10"
```

**Comment by sckott** [comment]
> defeats the purpose of the package.

I'd appreciate it if you change your tone, here and in other issues you've opened recently. It does not make me want to respond in a helpful and constructive fashion

**Comment by hlapp** [comment]
@sckott I'm sorry if I'm not hitting the right tone, but I'm really just reporting my observations of what I believe to be incorrect behavior of some piece of code, and as to why I believe the behavior is incorrect. I'm reporting it because the behavior of the code as is tripped up my test and it cost me some time to debug what's going on.

That's all. It's fine if you disagree and find that the code works correctly as is.

**Comment by sckott** [comment]
this should be fixed now. thanks for raising the issue.
