### ISSUE TITLE
Response header names retain case

### ISSUE THREAD

**Issue by hlapp** [ropensci/webmockr#49]
When setting response headers to be returned in a stub request, the header names do not get changed to lowercase when received by `crul`. This is different from the normal behavior (in `crul`) for response headers from actual web requests, where all header names will be converted to lower case.

```R
library(crul)
library(webmockr)
webmockr::enable()
stub <- webmockr::stub_request(uri = "http://httpbin.org/get") %>%
  webmockr::to_return(headers = list("Foo-Bar" = "baz"))
cli <- HttpClient$new(url = "http://httpbin.org/")
resp <- cli$get("get")
resp$response_headers
# $`Foo-Bar`
# [1] "baz"

```

I'm not sure whether this actually belongs here, or instead is an issue with `crul`? But since I believe the adapter for `crul` lives here, I thought I'd report it here first.

**Comment by sckott** [comment]
Thanks - I'll have a look. Right, it should return headers as they woul be returned in a real request

**Comment by sckott** [comment]
This should be fixed now
