### ISSUE TITLE
Dead link to user manual on CRAN

### ISSUE THREAD

**Issue by erzk** [ropensci/webmockr#71]
Link to [user manual](https://ropensci.github.io/http-testing-book/) on [CRAN](https://cran.r-project.org/web/packages/webmockr/) is dead.

DESCRIPTION file uses another URL: https://ropenscilabs.github.io/http-testing-book/

This could be a difference between dev and CRAN version but I thought it's worth raising an issue anyway.

**Comment by sckott** [comment]
thanks! Aware of that, and did fix it here already https://github.com/ropensci/webmockr/issues/67 Same problem with vcr. been meaning to get new versions up soon, but had some other issues to sort out first

**Comment by sckott** [comment]
thanks! Aware of that, and did fix it here already https://github.com/ropensci/webmockr/issues/67 Same problem with vcr. been meaning to get new versions up soon, but had some other issues to sort out first

**Comment by sckott** [comment]
sending to cran today
