### ISSUE TITLE
cleanup httr adapter test from recent PR

### ISSUE THREAD

**Issue by sckott** [ropensci/webmockr#89]
@aaronwolen one of the new tests is leaving a file on disk `empty.yml`. I tried the following briefly

```r
# cleanup
vcr::eject_cassette("empty")
unlink(cas$file())
```

it works for cleaning up the cassette file in the temp dir, but somehow there's an empty.yml file being created in the tests/testthat directory too. Or is this just happening to me?

**Comment by aaronwolen** [comment]
Not just you—I see it now too. I'll check it out.
