### ISSUE TITLE
Does one need enable() in tests using webmockr?

### ISSUE THREAD

**Issue by maelle** [ropensci/webmockr#94]
Maybe not? in https://books.ropensci.org/http-testing/webmockr-testing.html

And if not, when does one need it?

**Comment by maelle** [comment]
And if one enables webmockr, it seems it means all requests need a stub, so one cannot have a single stub in the registry? What if I want an error for one URL, but business as usual for others? Sorry if I'm missing something obvious in the docs.

**Comment by sckott** [comment]
I think best thing would be to do enable just before you want to use mocking, then disable right after that code block which should return http requests to normal. 

> What if I want an error for one URL, but business as usual for others? 

does business as usual mean mocking with webmockr or no mocking

**Comment by maelle** [comment]
No mocking, only mocking some http interactions (the ones I want to replace with errors)

**Comment by sckott** [comment]
okay. 

let me know if that flow works: 

```r
enable()
block of code to mock errors
disable()
```

**Comment by sckott** [comment]
@maelle ^^ when you get a chance

**Comment by maelle** [comment]
I opened a PR in ropenaq, it worked well. 

Does it mean any HTTP request happening in the block need a stub, or if there's no stub for a request in the block, a real request could be used? Or even a vcr cassette?

**Comment by sckott** [comment]
after running `enable()` you shouldn't be able to make real HTTP requests. But, you can run `enable()`, then enable real http requests with `webmockr_allow_net_connect()`. I don't know what would happen if you run `enable()`, then use vcr; i think it'd work fine, but haven't tried it.

**Comment by maelle** [comment]
I'll do more experiments in further PRs to ropenaq then, and report back. Thank you!

**Comment by sckott** [comment]
ok, thanks

**Comment by maelle** [comment]
Two further comments

* Instead of enabling/disabling I'd find it easier to have context so I'd write

```r
webmockr::with_webmockr({
  testthat::test_that("thing", {
    <code>
  })
})
```

* And I would still like a mixed behavior with some HTTP request allowed, although I realize it might be impossible. For any request within `with_webmockr`, if no stubs of the stub registry matches, do a real request instead. And maybe even save the real request to a vcr cassette. This way when testing I would use real responses most of the time, but fake a few.

**Comment by sckott** [comment]
You can already allow some http requests, see https://docs.ropensci.org/webmockr/reference/webmockr_configure.html

> if no stubs of the stub registry matches, do a real request instead

unfortunately, that's exactly opposite of the way the package works. when enabled, no http requests are allowed (other than ones you allow, see comment above). i imagine one could create a little wrapper that catches webmockr errors, and then disables webmockr if no stub is found

`with_webmockr` should be possible.

**Comment by maelle** [comment]
> with_webmockr should be possible.

Should I open a separate issue?

> i imagine one could create a little wrapper that catches webmockr errors, and then disables webmockr if no stub is found

but neither webmockr nor vcr would contain this wrapper, right?

**Comment by sckott** [comment]
yes, a separate issue would be good. 

It's already complicated, I don't want to add more complexity. I guess it seems confusing in that a thing called with_webmockr would make a real request if no stub is found (which webmockr normally would not allow), and then optionally save the request/response to disk (which vcr should be doing).  I like the clear distinction between webmockr that does not cache real requests/responses and vcr which does.

**Comment by maelle** [comment]
So, my thinking now is that it's just easier to use vcr cassettes for all the things and then edit a few by hand if needed. I'll open an issue with vcr. :-)
