### ISSUE TITLE
How do I access the passed body of a POST call?

### ISSUE THREAD

**Issue by matthewcornell** [ropensci/webmockr#98]
Hi Folks. Thanks very much for your work. Question: I have a `stub_request` call that's working fine, but I want to access the body that was passed to the stub so I can verify its correctness. However, I can't find where the requested content is located in the `StubbedRequest` returned by `stub_request`. Since your code is intercepting the POST, I must be missing something. Thank you!

```r
  stubbed_request <- webmockr::stub_request("post", uri = "http://example.com/api/projects/") %>%
    to_return(
      body = TWO_PROJECTS_JSON[[1]],
      status = 200,
      headers = list('Content-Type' = 'application/json; charset=utf-8'))
```

**Comment by sckott** [comment]
thanks for your question @matthewcornell 

if `stubbed_request` is your stub, you should be able to get to expected response parts by indexing like `stubbed_request$responses_sequences` - it's not the most intuitive flow i'll admit.  `stubbed_request$body` is for if you specify a body to match on with `wi_th()`, so that's not the response body you set with `to_return()`.  let me know if that works

**Comment by matthewcornell** [comment]
Thanks for your reply, @sckott . I apologize for not being clear. What I'm looking for is the actual body that was passed to `httr::POST()`. Here's an example. First, a simple function under test that POSTs what it's passed:

```r
do_post <- function(uri_to_post, body_to_post) {
  response <- httr::POST(
    url = uri_to_post,
    body = body_to_post
  )
  httr::content(response, "parsed")  # JSON response
}
```

Second, a test that stubs the POST:

```r
test_that("foo() 1", {
  uri_to_post_to <- "http://example.com/foo"
  body_to_post <- list(foo = "bar")
  body_to_return <- list(baz = "what comes after baz?")
  stubbed_request <- stub_request('post', uri = uri_to_post_to) %>%
    to_return(
      body = body_to_return,
      headers = list('Content-Type' = 'application/json; charset=utf-8'))
  expect_error(result <- do_post(uri_to_post_to, body_to_post), NA)
  expect_equal(result, body_to_return)
  expect_equal(stubbed_request$ACTUAL_POSTED_BODY, body_to_post)  # <- what I want
})
```

That `stubbed_request$ACTUAL_POSTED_BODY` property is what I'm after. HTH

**Comment by sckott** [comment]
okay. the body sent in the http request will only be in the stub object IF you create the stub with the request body. e.g,. 

```r
z <- stub_request('post', uri = uri_to_post_to) %>%
  wi_th(body = body_to_post) %>% 
  to_return(
    body = body_to_return,
    headers = list('Content-Type' = 'application/json; charset=utf-8'))
z$body
```

Alternatively, if you're function `do_post()` returned the httr response object you'd have the request body in it:

```r
do_post <- function(uri_to_post_to, body_to_post) {
  httr::POST(
    url = uri_to_post_to,
    body = body_to_post
  )
}
result <- do_post(uri_to_post_to, body_to_post)
result$request$fields
```

**Comment by matthewcornell** [comment]
Thanks. I try to avoid changing functions under test unless I have to, so let met ask about your first solution: Are you saying that the actual body POSTed by `do_post()` is not directly saved in `stubbed_request`? The point of my test is to make sure that `do_post` POSTs the correct content. (My example here is obviously contrived. In the real code, the POSTed body is more complicated.)

I feel like I'm missing something. Let me try this way: If my code under test did this:

```r
  response <- httr::POST(
    url = uri_to_post_to,
    body = list(foo = "bar")
  )
```

Then is there any way to get `list(foo = "bar")` back from `stubbed_request` without passing it via `wi_th`? That kind of defeats the purpose... ? Thank you.

**Comment by matthewcornell** [comment]
Maybe I'm misunderstanding the role of webmockr with respect to obtaining the actual content POSTed. Is there some other package that does this? I saw vcr mentioned, but a quick perusal left me confused :-O

**Comment by sckott** [comment]
- webmockr: is for mocking, it's goal is not to cache real http requests, but to let the user specify mock/fake responses 
- vcr: is for caching of real http requests, mostly for unit tests. it leverages webmockr to match requests

**Comment by sckott** [comment]
> Are you saying that the actual body POSTed by do_post() is not directly saved in stubbed_request?

correct. it breaks down like this:

`stub_request` creates a stub by matching against certain elements of an HTTP request.

if you do  `stub_request('post', uri = "https://httpbin.org/post")` you are matching on the http verb and the uri of the http request. 

if you do `stub_request('post', uri = "https://httpbin.org/post") %>% wi_th(body = list(foo = "bar"))` then you are matching on http verb, the uri of the request, and the body of the request

the `StubbedRequest` doesn't record the body sent in the request - in fact it could not, since the point of webmockr is to mock http requests, that is, not real http requests. (assuming you run `webmockr::enable()` first, which "turns on" webmockr)

**Comment by matthewcornell** [comment]
Thanks a ton for the info - that helps bring me up to speed a little better. It sounds like vcr is what I should check out next. Right now my approach (e.g., https://github.com/reichlab/zoltr/blob/bd93b5fc01d2d68799daca720ef2f7189f7687eb/tests/testthat/test-project.R#L12 ) is to use webmockr to stub the request, along with `testthat::with_mock()` to catch the call. I'm very new to R (Python is my background), so maybe it's not idea, but what I do is save the POST call's args and test against them. The issue is that I need an actual request object to return from the POST mock, which I do via a saved one in an rda file. The problem is that I get a warning when I build the package, and the CRAN people are really tough about allowing no warnings:

    WARNING: Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R

Anyway, thanks again for your work!

**Comment by sckott** [comment]
for the warning about R 3.5, try `save(object, file="yourfilename", version = 2)`

**Comment by sckott** [comment]
With regard to how you're using webmockr in your pkg, that's a valid way to use it. I would say `vcr` just does that for you, where you just wrap your function that makes an http request in `vcr::use_cassette()`, and it takes care of caching the http request and response so all subsequent test runs use that cached data. with `webmockr` though you get more control over those steps, so its really up to you what kind of interface you want, etc.

**Comment by matthewcornell** [comment]
Thanks a ton for that! Cheers.
